config/routes.rb
Rails.application.routes.draw do

  namespace :account do
    resources :groups
    resources :posts
  end

  devise_for :users # ??? 對user這個model使用devise
  root 'groups#index' #這行代表把localhsost:300/groups這個網址設為首頁
  resources :groups do # 用 for-loop 將groups連結到posts,網址對應/groups/1/posts/1
    member do        # ??? 對應到groups_controller和user.rb的 join quit
      post :join
      post :quit
    end

    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base # Group這class繼承Rails內建 ActiveRecord::Base的功能, 可讓我們透過Ruby語法操作資料庫 (sqlite3 , pg)
  #資料驗證: title欄位不能為空白
  validates :title, presence: {message: "此欄位不可以是空白!"}      # presence: true 也可以，會自動顯示 "can't be blank"

  has_many :posts, dependent: :destroy  # 建立與 post之間的資料庫關聯, 且當刪除group時所屬的posts也一併刪除
  has_many :group_users
  has_many :members, through: :group_users, source: :user

 # 建立與 user之前的資料庫關聯,在此 :owner等同於 :user,不管什麼名稱都會對應到user model
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner     # (user(存在/true)) && (user == owner)
  end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group, counter_cache: :posts_count #使用Rails model內建功能counter_cache, 在這裡設定好已加入group裡的對應欄位名稱 posts_count
  validates :content, presence: {message: "欄位不可為空白！"}

  belongs_to :author, class_name: "User", foreign_key: :user_id  # :author等同於 :user, 連接到user的model

  scope :recent, -> {order("updated_at DESC")}    # 在model內將常用到的功能.order(updated_at DESC) 用scope 定義成 :recent 來呼叫
                                                  # 有點像是將別人的名字 "自訂暱稱"一樣 , 如此即可在controller使用 .recent

  def editable_by?(user)
    user && user == author
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups  # 設定user與group之間的資料庫關聯
  has_many :posts  # 設定userposts之間的資料庫關聯

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  # 定義一個function is_member_of? 讓已存在的participated_groups使用include這個function來判斷現有的group是不是已經加入, 會回傳true or false
  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController

  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

  before_action :authenticate_user!

  def index
  #  @posts = current_user.posts.order("updated_at DESC")     # .order("updated_at DESC") 讓文章倒序排列(DESC) 最新 - 最舊
     @posts = current_user.posts.recent                      # 已在models/post.rb 使用scope將上面功能改叫作 .recent
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # 加入strong_parameters與devise整合的hack
  before_filter :configure_permitted_parameters, if: :devise_controller?   # Hash syntax a: b is equal to :a => b

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy] # 要求登入,需先安裝gem devise並執行rails g devise:install

  # controller骨幹 : index, show, new, edit, create, update, detroy , 其中作者可 edit create update destroy
  def index
    # flash[:warning] = "下午到了! 該睡午覺了!" -- 測試notice_message這個helper的功能是否正常使用
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def new
    @group = Group.new # 將@group設定成一個新物件, 格式與規則與app/models/group.rb裡的設定
  end

  def edit
    @group = current_user.groups.find(params[:id])   # 登入的使用者(current_user)所擁有的"group資料(.groups)"來找某筆資料(.find(params[:id])"
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      current_user.join!(@group)  # 讓使用者新增文章成功的同時自動成為group的ㄧ員
      redirect_to groups_path, notice: "新增討論版成功!"
    else
      render :new
    end
  end

  def update
    @group = current_user.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to groups_path, notice: "修改討論版成功!"
    else
      render :edit
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path, alert: "討論板已刪除"
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "加入本討論板成功！"
    else
      flash[:warning] = "你已經是本討論板成員了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出本討論板！"
    else
      flash[:warning] = "你不是本討論板成員，怎麼退出XD"
    end

    redirect_to group_path(@group)
  end

  private

  # 整串 Hash 參數 (params) 只允許 (.permit) group 資料表 (:group) 的 :title 跟 :description 這二個欄位的資料通過
  # 進入下一個階段的 SQL 資料庫存取，其餘的參數一律忽略
  def group_params
    params.require(:group).permit(:title, :description) #
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! # 要求登入,需先安裝gem devise並執行rails g devise:install ,posts只有5個actions,不需另外only:
  before_action :find_group    # 使用before_action先各個指定的action之前先執行 private內定義的find_group function
                               # 可在 :find_group後用 only: [:edit, :update]或 except: [:destroy] 以進行指定
                               # after_action  -- 執行完成action後的動作

  before_action :member_required, only: [:new, :create]  # 在底下private定義member_required,內容為對!current_user使用is_member_of?(已在user.rb定義)

  def new
    @post = @group.posts.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = @group.posts.build(post_params)
    @post.author = current_user

    if @post.save
      redirect_to group_path(@group), notice: "新增文章成功！"
    else
      render :new
    end

  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to group_path(@group), notice: "文章修改成功！"
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy
    redirect_to group_path(@group), alert: "文章已刪除"
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  # 使用before_action 定義find_group把每個action都有的重複code收進來，在最一開始執行 before_action :find_group
  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_required
    if !current_user.is_member_of?(@group)
      flash[:warning] = "你不是這個討論板的成員，無法發言"
      redirect_to group_path(@group)
    end
  end


end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = {notice: :success, alert: :danger}

    close_button_options = {class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    truncate(group.description, length: 55)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">
    Copyright ©2014 Rails101s <br>
    Design by <a href="http://sdlonglogdown.com" target=_new>sdlong</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101s</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li> <%= link_to("註冊", new_user_registration_path) %> </li>
        <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-roggle" data-toggle="dropdown">
            Hi!, <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("我的社團", account_groups_path) %> </li>
            <li> <%= link_to("我的留言", account_posts_path) %> </li>
            <li> <%= link_to("帳號設定", edit_user_registration_path )%> </li>
            <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: {class: "form-control"} %>
      <%= f.input :description, input_html: {class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %>
  <% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>修改討論版</h1>

  <hr>
    <%= render "form", group: @group %>   <!-- 將原先內容移到 views/groups/_form.html.erb -->
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(truncate(group.title, length: 15), group_path(group)) %></td>   <!-- truncate功能可限制顯示字數 ... -->
          <td><%= render_group_description(group) %></td>
          <td>
            <% if group.editable_by?(current_user) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),     class: "btn btn-sm btn-default",
                          method: :delete, data: {confirm: "Are you sure?"}) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增討論版</h1>

  <hr>
    <%= render "form", group: @group %>  <!-- 將原先內容移到partial  views/groups/_form.html.erb -->
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新增文章", new_group_post_path(@group), class: "btn btn-primary btn-warning pull-right") %>
    <% if @group.editable_by?(current_user) %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right") %>
    <% end %>

    <% if current_user.present? %>
      <% if current_user.is_member_of?(@group) %>
      <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-danger") %>

      <% else %>
      <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-info") %>
      <% end %>
    <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p> <%= @group.description %></p>

  <table class="table">
    <thead>
      <tr>
        <th>文章</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td><%= simple_format(post.content) %></td> <!-- simple_format 可讓內容顯示自動斷行 -->
        <td>
          <% if post.editable_by?(current_user) %>
            <%= link_to("Edit", edit_group_post_path(post.group, post), class: "btn btn-default btn-xs") %>
            <%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete,
                         data: {confirm: "Are you sure>"}) %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101s2nd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  <!-- 應該是灌完bootstrap-sass後自動產生 -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">  <!-- container-fluid 讓網頁左右留白邊 -->
<%= render "common/navbar" %>  <!-- 引用partial  views/common/_navbar.html.erb -->
<%= notice_message %>          <!-- 使用flash message -->
<%= yield %>                   <!-- 各個網頁內容主體 -->
</div>
<%= render "common/footer" %>  <!-- 引用partial views/common/_footer.html.erb -->

</body>
</html>

app/views/posts/edit.html.erb
<h1 class="text-center">修改文章</h1>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: {class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submittiing...", class: "btn btn-primary"%>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center">新增文章</h1>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group,@post] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: {class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submittiing...", class: "btn btn-primary"%>
    </div>
    <% end %>
</div>